### ISSUE TITLE
Add bundled case for FEC Draft

### ISSUE THREAD

**Issue by gmandyam** [juberti/draughts#12]
Suggested changes follow.  Note slight change to current Sec. 5.1.  Would recommend adding new section after current Section 5.1. 
```
<!ENTITY rfc6363 SYSTEM "http://xml.resource.org/public/rfc/bibxml/reference.RFC.6363.xml">
<!ENTITY rfc6681 SYSTEM "http://xml.resource.org/public/rfc/bibxml/reference.RFC.6681.xml">

<section title="Recommended Mechanism">
  <t>
    For video content, use of a separate FEC stream with the RTP payload format
    described in <xref target="I-D.singh-payload-rtp-1d2d-parity-scheme"/> is RECOMMENDED.
    The receiver can demultiplex the incoming FEC stream by SSRC and correlate it
    with the primary stream via the ssrc-group mechanism.
  </t>
  <t>
    Note that this only allows the FEC stream to protect a single primary stream (as identified by an SSRC).
    Support for protecting multiple primary streams with a single FEC stream is
    complicated by WebRTC's 1-m-line-per-stream policy and requires further study.
  </t>
</section>

<section title="FEC for Bundled Protection">
  <t>
    <xref target="RFC6363"/> provides for the ability to protect several source flows together.  For instance, it may be desirable under certain conditions to 
    provide bundled protection for multiple video flows along with a single mixed audio flow in a teleconference scenario.  Depending on the FEC scheme chosen,
    the bundled flows may be indicated through the source and repair flow headers described in Section 5 of <xref target="RFC6363"/>.  For instance, <xref target="RFC6681"/>
    does not require a source FEC payload ID but simply leverages the target RTP source stream (that could include multiple CSRC's) along with the associated sequence
    number.  The repair RTP flow, which is assumed to have its own SSRC, uses a repair FEC payload ID constructed as per the procedures outlined in Sections 8.1.3
    and 8.2.4 of <xref target="RFC6681"/>.
  </t>
</section>

<references title="Normative References">
  &rfc2119;
  &rfc2198;
  &rfc5956;
  &rfc6363;
  &fecpayload;
</references>

<references title="Informative References">
  &rfc5109;
  &rfc6716;
  &rfc6681;
  &opuspayload;
</references>
```

**Comment by juberti** [comment]
putting in a more readable format:

    <xref target="RFC6363"/> provides for the ability to protect several source flows together.  For instance, it may be desirable under certain conditions to provide bundled protection for multiple video flows along with a single mixed audio flow in a teleconference scenario.  Depending on the FEC scheme chosen, the bundled flows may be indicated through the source and repair flow headers described in Section 5 of <xref target="RFC6363"/>.  For instance, <xref target="RFC6681"/> does not require a source FEC payload ID but simply leverages the target RTP source stream (that could include multiple CSRC's) along with the associated sequence number.  The repair RTP flow, which is assumed to have its own SSRC, uses a repair FEC payload ID constructed as per the procedures outlined in Sections 8.1.3 and 8.2.4 of <xref target="RFC6681"/>.

**Comment by juberti** [comment]
I read this a few times but I have to say I don't understand exactly what you are suggesting. Can you explain a bit more for me how this multi-stream protection would work, exactly?
