### ISSUE TITLE
[nombis] Suggested Diagrams

### ISSUE THREAD

**Issue by emcho** [juberti/draughts#14]
Suggested diagrams for the examples currently in the draft. May change as the draft progresses.

https://www.dropbox.com/s/kaa30k4gglqbvc8/nombis-diags.txt?dl=0

I'd be happy to make a PR but the draft here doesn't seem to be the latest version.

**Comment by juberti** [comment]
I pushed the latest text this morning. These diagrams LG - I think we should probably add more detail during the sections where the new candidates are checked, but we can add that later. Please send a PR.

**Comment by juberti** [comment]
I concur which is why I think we should do it later.
