### ISSUE TITLE
FEC: RFC2198 citation needed

### ISSUE THREAD

**Issue by juberti** [juberti/draughts#46]
> 1. Section 4.2:
> 
>    Support for redundant encoding MUST be indicated by offering "red" as
>    a supported payload type in the offer.
> 
> I think it is unclear what "red" refers to here. This as it is not made clear that RFC 2198 has the media type audio/red and text/red. I think there are two things that would make this clearer. One would be to change "red" into media type "audio/red". The other would be to add the reference afterwards.

Justin: adding ref seems like the right solution.

**Comment by gloinul** [comment]
I would note that Section 4.2 is the first time the term "offer" is used in this document. This is not the JSEP document, so a bit of context indicating that one refers to "red" in an SDP O/A context would be good. That can either be clarified by indicating what type of "offer" on refers to or indicate that one is offering a media type with the sub-type "red".

**Comment by juberti** [comment]
OK, I see what you mean. I worked both into the document, it ended up being fairly simple.
