### ISSUE TITLE
Rephrase s3 more simply

### ISSUE THREAD

**Issue by seanturner** [juberti/draughts#50]
from Martin Thomson's email on ip-handling:
https://mailarchive.ietf.org/arch/msg/rtcweb/u8EEn0Oz05I86WqpT2PiTvZVcXA

In Section 3, please don't imply that WebRTC is only for privacy.  At
a minimum "Being peer-to-peer, WebRTC represents a technology that
could improve privacy,"  Though I'd avoid this sort of statement
altogether.  One interesting side effect of unintermediated or
peer-to-peer communications is that there is now network-level
metadata showing who was communicating.  There is a direct flow
between peers.  The privacy gain (no single middleman with access to
communications metadata) becomes a potential loss (passive network
observers can see who was talking more easily).

I think that Section 3 could be more simply stated as:

Provide a framework for understanding the problem so that controls
might be provided to make different trade-offs regarding performance
and privacy concerns with WebRTC.  Using that framework, define
settings that enable peer-to-peer communications each with a different
balance between performance and privacy.  Finally, provide
recommendations about settings that provide reasonable performance
without also exposing addressing information in a way that might
violate user expectations.

**Comment by juberti** [comment]
@martinthomson:
The point of the privacy sentence was to provide a clear answer to why limiting WebRTC could be a negative from a privacy perspective. Agree the sentence may overreach, but I think it's worth keeping in some form.

Your rewording of the goals is good. I think 'default' needs to be worked into the last sentence though.

**Comment by martinthomson** [comment]
Yeah, sounds good: "recommendations about *default* settings" should do.
