### ISSUE TITLE
Remove mention of RETURN in s4

### ISSUE THREAD

**Issue by seanturner** [juberti/draughts#51]
From Martin Thomson's email on ip-handling:
https://mailarchive.ietf.org/arch/msg/rtcweb/u8EEn0Oz05I86WqpT2PiTvZVcXA

In Section 4, the mention of RETURN isn't really necessary and it will
stall progress of this draft.  The framing of RETURN ensures that it
falls into the "proxy" definition quite neatly, so it will work
without changing this draft.  Though RETURN would reduce the
performance downsides of the higher-numbered modes - significantly -
it doesn't really need a special mention here.

**Comment by juberti** [comment]
May be useful to mention that future proxies may exist that will address the TCP proxy challenges.
