### ISSUE TITLE
Question about IP discovery

### ISSUE THREAD

**Issue by seanturner** [juberti/draughts#59]
From Bernard's [review](https://mailarchive.ietf.org/arch/msg/rtcweb/Za9SAmzuw-Fgv1KOB51xwgY2Ejs) posted to the list:

In section 2  [Problem Statement](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-03#section-2)

    2.  If the client tries to hide its physical location through a VPN,
        and the VPN and local OS support routing over multiple interfaces
        (i.e., a "split-tunnel" VPN), WebRTC will discover the public
        address for the VPN as well as the ISP public address that the
        VPN runs over.

[BA] Even if the local OS doesn't support split-tunnel,
isn't it still possible for an ICE implementation to
discover other addresses?

**Comment by juberti** [comment]
@aboba: Yes, but those are typically RFC1918 addresses, which are discussed in bullet #1.

**Comment by juberti** [comment]
Any other comments on this? I think this is already covered in the document. (cc @spt)

**Comment by seanturner** [comment]
At this point, I'm thinking you should close this one.
