### ISSUE TITLE
Should a goal be to enable WebRTC to be used with Tor?

### ISSUE THREAD

**Issue by seanturner** [juberti/draughts#60]
From Bernard's [review](https://mailarchive.ietf.org/arch/msg/rtcweb/Za9SAmzuw-Fgv1KOB51xwgY2Ejs) posted to the list:

In section 3  [Goals](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-03#section-3):

    Being peer-to-peer, WebRTC represents a privacy-enabling technology,
    and therefore we want to avoid solutions that disable WebRTC or make
    it harder to use.  This means that WebRTC should be configured by
    default to only reveal the minimum amount of information needed to
    establish a performant WebRTC session, while providing options to
    reveal additional information upon user consent, or further limit
    this information if the user has specifically requested this.
    Specifically, WebRTC should:

    o  Provide a privacy-friendly default behavior which strikes the
       right balance between privacy and media performance for most users
       and use cases.

    o  For users who care more about one versus the other, provide a
       means to customize the experience.

[BA] This section might state whether it is a  goal to enable WebRTC to be used with  The Onion Routing network (Tor). There are a number of reasons why enabling Javascript for  use with Tor may represent a problem so that use of WebRTC might not be advisable:
https://security.stackexchange.com/questions/95046/why-disable-javascript-in-tor

**Comment by juberti** [comment]
@aboba, it looks like the default Tor bundle does allow use of JS, which makes it somewhat problematic to argue against here, given that one could support Tor with Mode 4.

**Comment by juberti** [comment]
@spt, any thoughts on this?

**Comment by juberti** [comment]
Agreed on list, the section on proxies covers this implicitly.
