### ISSUE TITLE
Simplify default discovery paragraph

### ISSUE THREAD

**Issue by seanturner** [juberti/draughts#61]
From Bernard's [review](https://mailarchive.ietf.org/arch/msg/rtcweb/Za9SAmzuw-Fgv1KOB51xwgY2Ejs) posted to the list:

4 [Detailed Design](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-03#section-4):

    1.  By default, WebRTC should follow normal IP routing rules, to the
        extent that this is easy to determine (i.e., not considering
        proxies).  This can be accomplished by binding local sockets to
        the wildcard addresses (0.0.0.0 for IPv4, :: for IPv6), which
        allows the OS to route WebRTC traffic the same way as it would
        HTTP traffic, and allows only the 'typical' public addresses to
        be discovered.

[BA] This paragraph discusses routing behavior and address binding together and leads me to wonder whether some assumptions aren't being made (e.g. weak versus strong host model).  My suggestion is to simplify the the paragraph and leave details to later on. For example:

    1. By default WebRTC should only allow applications
       to discover the same address information made available
       by an HTTP application: the 'typical' public address.

**Comment by juberti** [comment]
@aboba: This removes some of the important nuance from the statement, namely that about proxies.

Agree that the info about wildcard binding could be moved later to the mode definitions, although I don't follow exactly what you mean by 'weak vs strong host model'.

**Comment by juberti** [comment]
Looked into host models and I don't think this changes the situation meaningfully.

Overall plan here should be to separate the principles from the implementation guidance, as alluded to in the Jul 3 comment.
