### ISSUE TITLE
Specify Flex FEC and SRTP/DTLS order

### ISSUE THREAD

**Issue by murillo128** [juberti/draughts#77]
It seems that in the latest FLex FEC draft, the mention to the default processing order has been removed:

https://www.ietf.org/rfcdiff?url2=draft-ietf-payload-flexible-fec-scheme-05

IMHO we should explicitly state which is the default processing order for WebRTC to avoid misinterpretations.

**Comment by juberti** [comment]
This is covered in the latest text, in the security considerations section.

**Comment by murillo128** [comment]
Thanks! I missed that change, sorry for the noise.
